[server]
bind_addr = "0.0.0.0:2333"

[server.services.rdp_pc1]
token = "sigma"
bind_addr = "0.0.0.0:33891"

[server.services.rdp_pc2]
token = "sigma"
bind_addr = "0.0.0.0:33892"

[server.services.rdp_pc3]
token = "sigma"
bind_addr = "0.0.0.0:33893"

[server.services.rdp_pc4]
token = "sigma"
bind_addr = "0.0.0.0:33894"

[server.services.rdp_pc5]
token = "sigma"
bind_addr = "0.0.0.0:33895"

[server.services.rdp_pc6]
token = "sigma"
bind_addr = "0.0.0.0:33896"

[server.services.minecraft_pc1]
token = "sigma"
bind_addr = "0.0.0.0:25565"
